FROM ubuntu

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update
RUN apt-get install -y apt-utils vim curl apache2 apache2-utils openssh-server
RUN apt-get -y install python3 libapache2-mod-wsgi-py3
RUN apt purge python2.7-minimal
RUN ln /usr/bin/python3 /usr/bin/python
RUN apt-get -y install python3-pip
# RUN ln /usr/bin/pip3 /usr/bin/pip
RUN pip install --upgrade pip
RUN pip install django
ADD ./configuratie.conf /etc/apache2/sites-available/000-default.conf
EXPOSE 80

RUN apt-get install -y git
RUN mkdir /root/.ssh/
ADD id_rsa /root/.ssh/id_rsa
RUN chmod 400 /root/.ssh/id_rsa
RUN touch /root/.ssh/known_hosts
RUN ./etc/init.d/ssh start && ssh-keyscan gitlab.fdmci.hva.nl >> /root/.ssh/known_hosts
RUN git clone git@gitlab.fdmci.hva.nl:mohunlr/pad_t22.git

CMD cd /pad_t22 && git pull && apache2ctl -D FOREGROUND
